name: FastTNT
main: com.github.jikoo.fasttnt.FastTNT
version: 1.4.2
author: Jikoo
softdepend: [Vault]

permissions:
 fasttnt.*:
  default: op
  children:
   fasttnt.reload:
    default: op
    children:
     fasttnt.use:
      default: true

commands:
 fasttnt:
  description: Craft TNT in a jiffy!
  permission: fasttnt.use
  aliases: [ftnt, tnt, ctnt]
  usage: /fasttnt [number] or just /fasttnt to craft as many as possible
